### ISSUE TITLE
Institution add form

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#1]
Below the 'Organization' field in submit forms, where users set organizations, we'll have a text:

> If your organization is not listed in the dropdown, please complete the New Organization form. If you wish to submit multiple resources, please wait until the form has been processed (1-3 days) before submitting your resources

Clicking on it makes a little form appear (directly below, but visually a bit distinct) where the user can add the data for a new organization. Fields are:
- Name of organization (open text) - helptext: “please include the full name of the organization without abbreviations”
- City (open text)
- State or Province (open text)
- Country
- Organization’s primary website (open text - valid URL)
- Organization type (dropdown - make consistent with the filter dropdown options)
- Student FTE (numeric entry - make consistent with the institution size dropdown options) - ideally make this conditionally required if they selected one of the higher ed options for org type. Otherwise, make optional.

**Comment by monika-aashe** [comment]
I found a typo in 2nd sentence: "If your if you" - remove "your if" so it says "If you wish..."

**Comment by monika-aashe** [comment]
Changing priority level - something we'd like to test and have ready before releasing Phase 1

**Comment by monika-aashe** [comment]
Add help-text.

**Comment by dodget** [comment]
Since Institution/Organization data is now coming from the ISS, I don't think that this would be the best approach in terms of data management. I also haven't heard this come up as a desired feature.

I'm going to close this as it appears to be both stale, and not very feasible with the Hubs current design. This was the first issue registered for the Hub, so that's cool.
