### ISSUE TITLE
Image should appear prominently for Photograph resources

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#118]
Ideally, the cover image would appear to the right of the following info right below the title and org:
Date Published: Nov. 22, 2015
Last Updated: Nov. 22, 2015
Sustainability Topic: Wellbeing & Work
Content Type: Publications
Discipline: Agriculture
Release Date: Sept. 1, 2015
Publisher: AASHE

It shows up really low on the page, and isn't noticeable unless you scroll. http://aashe-hub-dev.herokuapp.com/browse/publication/47/2015-Sustainability-Staffing-Survey

**Comment by jamstooks** [comment]
Additional comments from #94

>When submitting an image under the "Image" field (not under Optional metadata), the image does not appear once the resource is approved: http://aashe-hub-dev.herokuapp.com/browse/photograph/13/Annie-Leonard-with-AASHE-2014-attendees - it does show up in admin.
>The image should visually show up under the resource detail - not just a "download" icon. See this submitted resource as an example (http://aashe-hub-dev.herokuapp.com/browse/publication/47/2015-Sustainability-Staffing-Survey)

**Comment by monika-aashe** [comment]
Note that images are also optional uploads for Case Studies, Conference Presentations, and Outreach Materials. I think it would be fine to treat them all the same (embedded image rather than download image option). 

For Photographs, the image is required - should be fine to treat this the same as well.

For all other content types, there should be no image upload option.

**Comment by jamstooks** [comment]
How do you like this setup?

http://aashe-hub-dev.herokuapp.com/browse/photograph/76/Test-Photos-from-Ben

Any resource with images attached would have them displayed like this.
