### ISSUE TITLE
Filter: Country and State field

### ISSUE THREAD

**Issue by bartTC** [AASHE/hub#14]
Country: 
- Countries should be listed alphabetically with no blank spaces. Right now, the list is Canada, Australia, [blank], and United States. Need to remove blank.
- Allow for selecting more than one.

States:
Selecting Canada only should make Canadian provinces pop-up only. Selecting United States only should make U.S. states show up only. Selecting All or U.S. and Canada should make both state and province lists show up. Right now, both US states and Canadian provinces show up if U.S. or Canada is selected.

**Comment by monika-aashe** [comment]
Reopened because the states are no longer showing up when you select Canada or U.S. - Also, can't select multiple countries.

**Comment by jamstooks** [comment]
I have this working again, but I'm thinking the design might need a little tweaking, for two reasons.

1. If you select either the US or Canada, you see all the states for both. Was this a deliberate design decision?
2. The lists are long and should really include some scrolling aids.

**Comment by juliandsmith** [comment]
Agree on the scrolling aides! Showing all 50 states in one long doesn't seem optimal. 

I also don't see a good reason to have the US states show up when Canada is selected and vice versa. From my perspective, it would be best if the state field were always visible in some form so that people would realize state filtering possible. Perhaps it could be grayed out or say something like "Select a country for this list to populate". People interested in state level filtering might not think to select country first.

**Comment by monika-aashe** [comment]
1/27/16 update - seems to be working pretty well, except that I'm unable to select multiple countries. Consider fixing this and updating style to checkboxes instead of dropdown (unless that messes with the automatic state filter that pops up.

**Comment by juliandsmith** [comment]
Countries should be listed alphabetically in with no blank spaces. Right now, the list is Canada, Australia, [blank], and United States.
