### ISSUE TITLE
Add editable text block to the top of each submission form

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#171]
Program staff will add submission instructions explaining what types of materials are supposed to be submitted under that content type.

**Comment by jamstooks** [comment]
Since the submit template () is shared for all resource-types, you'll have to do things a little differently this time. You can still use django-block-content, but the key will depend on the context variable, `content_type_label`. You'll want to concatenate it with something, like "_submit_form."

Two options:

1. Add a context variable to the view that does the concatenation
2. Use `with` in the template to create the key (preferred, I think):

        {% with content_type_label|add:"_submit_form" as key %}
        {% block_content key %}
        {% endwith %}

**Comment by baronvonvaderham** [comment]
This is done in the branch scott-dev and ready for deployment. Was hoping breadcrumb ticket might be quick enough to bundle those into a single PR.

**Comment by jamstooks** [comment]
Cool. Let me know when you're ready for that pull request.
