### ISSUE TITLE
Updates to all help-text throughout submission forms

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#188]
We need to make changes to the help-text before soft-launch. Here is the file: https://docs.google.com/spreadsheets/d/1P_oCu4m64G41XuMlCwUj7_KceL5Gj1I_gd-bmRN9q2U/edit#gid=2105030352

Basically, any time the help-text is in red, it means it requires a change.

**Comment by monika-aashe** [comment]
Decision needed, will be ready by 2/3/16 - @juliandsmith - I'm adding this to our call to discuss any additional changes to helptext.

**Comment by monika-aashe** [comment]
Okay @jamstooks , the list of help text changes is final.

**Comment by jamstooks** [comment]
@monika-aashe - I didn't realize you were looking for help text that differed by content type. I think we may have talked about the difficulties of this early on. It's certainly not impossible, but this is going to require much more time than I had anticipated.

The format of the linked spreadsheet makes comparison difficult. Are there significant differences between help text for similar fields between content types?

**Comment by jamstooks** [comment]
Development notes:

Since we're using the modelform factory, we don't really have access to the `help_texts` meta property of `ModelForm`.  The two other options that come to mind for variable help text are:

1. Create a reusable app that allows admins to manage help text for model/field
2. Write a hard-coded dictionary or something like that to update helptext

Option 1 is definitely preferable, but might be a little tricky. Maybe implement it a bit like the `@python_2_unicode_compatible` decorator for models. I'm not really sure if that would really work at the model level.

A third option would be to create some sort of template-tag that works like the `trans` tag to display content-specific help text. I'm gonna sit with these options for a bit before I start on one.

**Comment by monika-aashe** [comment]
@jamstooks - Most of the common fields help text is the same, but in some cases, it has to be different due to differences in whether a field is required for a particular content type. 

I've created a summary tab that should be helpful in showing which text should appear where: https://docs.google.com/spreadsheets/d/1P_oCu4m64G41XuMlCwUj7_KceL5Gj1I_gd-bmRN9q2U/edit#gid=1259421087

**Comment by monika-aashe** [comment]
@jamstooks - All of the final helptext edits are in. Feel free to update the helptext using the info in this Google sheet: https://docs.google.com/spreadsheets/d/1P_oCu4m64G41XuMlCwUj7_KceL5Gj1I_gd-bmRN9q2U/edit#gid=1259421087

**Comment by monika-aashe** [comment]
FYI @jamstooks - there is one helptext edit I missed in the original doc that I just added. 

Under the Files field, we need to remove the current helptext: "Valid formats are acceptable: PDF, Excel, Word, PPT..." it has a typo and isn't necessary anyway, so it can just be blank.
