### ISSUE TITLE
"AS" degrees are rendered as "As"

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#260]
For some reason, the AS (as in Associate of Science) degree programs are showing up with the s in lowercase (i.e., As instead of AS) in both search results and resource pages. Capitalization is correct on the admin side so this is purely an issue of how the letters are being rendered on the front end. Here are two examples:
http://hub.aashe.org/browse/academicprogram/12997/agroecology-as
http://hub.aashe.org/browse/academicprogram/12981/as-in-environmental-landscaping

For some reason, this doesn't not seem to be an issue with other degree types - BA, MS, AAS etc. all seem to be capitalized correctly.

**Comment by rerb** [comment]
Maybe because AS is a word. 

> On Mar 26, 2016, at 9:39 AM, juliandsmith <notifications@github.com> wrote:
> 
> For some reason, the AS (as in Associate of Science) degree programs are showing up with the s in lowercase (i.e., As instead of AS) in both search results and resource pages. Capitalization is correct on the admin side so this is purely an issue of how the letters are being rendered on the front end. Here are two examples:
> http://hub.aashe.org/browse/academicprogram/12997/agroecology-as
> http://hub.aashe.org/browse/academicprogram/12981/as-in-environmental-landscaping
> 
> For some reason, this doesn't not seem to be an issue with other degree types - BA, MS, AAS etc. all seem to be capitalized correctly.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

-- 
Attend the Sustainability Officers Retreat 
<http://www.aashe.org/events/workshops/2016/Sustainability-Officers-Retreat> at 
the University of British Columbia Okanagan Campus on July 27 - 29. 
Applications are due by April 15.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Yeah @rerb was right, there was a 'titlecase' filter being applied, so since "AS" is a word, it got filtered to have just a leading capital instead of all.

**Comment by jamstooks** [comment]
@baronvonvaderham - I'm not sure that simply removing the titlecase filter is the best solution to this issue. It may however, be the easiest and the one that makes the most sense. [The filter we use](https://github.com/chrisdrackett/django-typogrify#titlecase) doesn't support acronyms and I don't see any better options out there. Additionally, if we did go that route, we would need to remove it from the titles in the lists of resources too.

This was a requested feature for titles back in December, so I'll just communicate the issue here to @juliandsmith and @monika-aashe to keep y'all in the loop...

Right now now it feels like a tradeoff between converting all resource titles to "title case" automatically, or maintaining capitalized acronyms and the capitalization used during submission. Actually, more honestly there is third option in the tradeoff... a fair bit of time refactoring the titlecase filter to support acronyms. This is a complicated algorithm so it's a non-trivial task.
