### ISSUE TITLE
Add "Not a Member?" text to log-in page

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#277]
Here is the content we currently include:
<img width="372" alt="screen shot 2016-04-11 at 1 17 46 pm" src="https://cloud.githubusercontent.com/assets/15214797/14436139/49cf4602-ffe9-11e5-9c17-2c5cfe5b1ee6.png">

Final changes for below the log-in button:

**Forget your Password?**
[Click here](http://www.aashe.org/user/password) to reset your password.

**Don't Have an AASHE Account?**
[Create one](http://www.aashe.org/user/register) now. Anyone with an email address from a [member organization](http://www.aashe.org/membership/member-directory) can access our member-only resources.

**Not a Member?**
Learn about the [benefits](http://www.aashe.org/membership) of AASHE membership and join today!

**Comment by jessicaaasheaashe** [comment]
@monika-aashe Your suggested text changes work for me! Thanks!

**Comment by juliandsmith** [comment]
I'm okay with this, but let's have the Not a Member? text below the Don't have an AASHE Account text so that it's ordered by level of connectedness to AASHE (i.e., has an account, is a member but no account, and not even a member yet). 

Also, let's link "member organization" under the Don't have an AASHE Account to our member directory (http://www.aashe.org/membership/member-directory) so that people can easily determine if they are or are not a member.

**Comment by monika-aashe** [comment]
Okay, thanks, I've updated based on the feedback.
