### ISSUE TITLE
oregonstate.edu still shows up in Hub, even though it was updated in Salesforce last week

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#282]
Should also check to see if a new organization is going into the Hub.

**Comment by jamstooks** [comment]
@rerb do you think you'd have time to look into this this week?

**Comment by rerb** [comment]
Will do.

On Wed, Apr 27, 2016 at 4:15 PM, Benjamin W Stookey <
notifications@github.com> wrote:

> @rerb <https://github.com/rerb> do you think you'd have time to look into
> this this week?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/282#issuecomment-215214468>
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by rerb** [comment]
I'm missing something.  Oregon State is a member, but you don't want it in the Hub?  Is that true?  Also, not sure what to check for to "see if a new organization is going into the Hub."

**Comment by monika-aashe** [comment]
@rerb - "Oregon State University" is in the Hub and we want it to stay that way. However, "[oregonstate.edu](https://hub.aashe.org/browse/?search=&organizations=91473&country=)" is also in the Hub, and that is a mistake and needs to be deleted.

**Comment by monika-aashe** [comment]
Actually, Bob, I am working on a new ticket that has several of these types of issues. I'll update this comment when it's ready.

**Comment by monika-aashe** [comment]
@rerb - I'm closing this ticket in favor of #312 , which has this and about a half dozen similar issues that we'd like to have cleaned up. Let me know if you have any questions.

**Comment by rerb** [comment]
Still a bit confused on this one -- what was updated in Salesforce?  Was
there a Salesforce account called "oregonstate.edu"?  What was the update
in Salesforce?

On Tue, May 3, 2016 at 12:41 PM, monika-aashe <notifications@github.com>
wrote:

> Closed #282 <https://github.com/AASHE/hub/issues/282>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/282#event-649102230>
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
I think there was a salesforce account called oregonstate.edu at one time, but it has since been removed.  There might be a larger issue to address because it looks like accounts like this are being automatically created in Salesforce. I'm working with Chris to address this and will ask Ben about it too. Will keep you posted.

**Comment by jamstooks** [comment]
@rerb what seems to be going on here is that there is still an org in the iss with org_name == 'oregonstate.edu', but that record has been removed from SF. Do you think this is an issue with the iss shared app not deleting removed orgs?

**Comment by rerb** [comment]
The ISS app doesn't care about organizations that get deleted in
Salesforce, just new ones and ones that have been updated.  It asks only
for data on all Accounts added or modified since a point in time.  Are
Salesforce Accounts really deleted (or, e.g., just flagged as deleted)?  If
they're gone, we can't ask for ones deleted since a point in time since
they're gone.  Maybe we have to, instead, ask for the complete list of
Accounts and compare them to the iss.Organization table, deleting
Organizations that don't match an Account.  If they're just flagged then
maybe we should carry that flag forward into the iss.Organization record
and adjust the queries.  In any case, this is going to take a little time
to figure out.  (Not a lot of time, but maybe more than
"in-between-2.1-bug-fixes" time.) In the meantime, can the offensive
organizations be deleted from the Hub through the admin?

On Wed, May 4, 2016 at 12:27 PM, Benjamin W Stookey <
notifications@github.com> wrote:

> @rerb <https://github.com/rerb> what seems to be going on here is that
> there is still an org in the iss with org_name == 'oregonstate.edu', but
> that record has been removed from SF. Do you think this is an issue with
> the iss shared app not deleting removed orgs?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/282#issuecomment-216920045>
>



-- 
Robert Erb
Web Application Developer
Association for the Advancement of Sustainability in Higher Education
www.aashe.org | bob.erb@aashe.org | (888) 347-9997 ext 35

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by monika-aashe** [comment]
That makes sense. Whenever I update a record by changing "Membership Status" to "Not eligible for Membership" or checking "Exclude Account from AASHE Website", it no longer shows up in the Hub. But if I simply delete an account in Salesforce without making these modifications, it stays in the Hub. I'm not sure if the duplicate orgs can be deleted via admin. If this is possible for me to do, I'd love to learn how.

**Comment by jamstooks** [comment]
@rerb we can't modify orgs in the admin currently. It might be as simple as adding an admin.py file to the [iss app](https://github.com/AASHE/iss), but you might have to double check the [metadata.Organization](https://github.com/AASHE/hub/blob/master/hub/apps/metadata/models.py#L151) proxy model...

Depending on how tricky that gets, it might just make sense to remove those orgs manually using the shell in the short term.

**Comment by rerb** [comment]
oregonstate.edu deleted.
