### ISSUE TITLE
Image gallery toggle

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#313]
There is a need to better showcase some of the great images we're collecting through the Hub, and this could also be useful for AASHE staff internal use. 

Decision (July 27): Create a gallery toggle in all list, search and filtered results views.
- Toggle should appear near top of page: List View | Gallery View

List view:
- If a resource has multiple images, display as a collage view.
- Make image thumbnails large enough to see what is happening in image(s)

Gallery view:
- Include download image and bulk download for multiple images (staff only).

Discussion/decision needed:
- Should we also provide tabs or embedded blocks/image carousels in the sustainability topic pages?
- Should the gallery view include resources that don't have images, just placeholders? Or should it be a filtered view that only includes resources with at least 1 image? 
- Will the gallery view include filters at left (ideal if it would)?
- What happens if a view contains no images? Is there a default "no results" statement? 
- What gets displayed in the gallery view? 
     - Resource Title
     - Image thumbnail
     - Caption
     - Photographer credit?

**Comment by monika-aashe** [comment]
Moved to inbox in light of Andrea's request.

**Comment by monika-aashe** [comment]
Andrea: Best option for internal staff purposes would be Images tab on main home page that would access all images across all content types.

**Comment by monika-aashe** [comment]
Ben: Gallery view would automatically disable the filter since there are multiple images in some resource entries.

**Comment by monika-aashe** [comment]
Decision:
- No placeholder - can either make it not possible to view placeholder data, or by default, you get the filtered for must contain images list, but can click other filters to view placeholder resources.

**Comment by jamstooks** [comment]
I have temporarily assigned this to @baronvonvaderham. if you get to it this week, that's awesome, but if not, I should be able to finish it up when I get back.

**Comment by jamstooks** [comment]
Hey @monika-aashe and @juliandsmith - I have the gallery toggle feature up on my dev site:

https://aashe-hub-dev-ben.herokuapp.com/browse/types/outreachmaterial/?content_type=outreachmaterial&gallery_view=gallery

There are a few issues:

 1. the photographs content type seems to be cached so the thumbnails aren't showing up
 2. I've change the "# of results" display to "# of resources" - because resources can have more than one image associated with them, this is a bit of a half-measure. It might be better to change that to display the "# of images," but that's actually a lot of work and a simple solution would slow down the load time as it's currently designed, so it would require work to do it efficiently.

If this is ready to go, we can merge it in and get it going.

Also, please feel free to add any resources you'd like to this site.

**Comment by monika-aashe** [comment]
Looks nice! I do have a couple of questions/comments, but since you're on VACATION, I think it's okay for us to wait to discuss on Wednesday's Hub call.

1. While I like the toggle with diagrams, it might be clearer to include text such as "list view" and "gallery view" (or both). Or include some hover-over help text. I'd be interested to hear what others think. 
2) Can we ensure that the toggle only appears for views where one or more images are submitted? For example, the Academic Programs, Research Institutes, Course Materials, Tools, Videos Content Types don't allow for image uploads, so in the list views on these pages, the Toggle should remain hidden.
3) I like saying "x Resources" on list view and "x Images" on Gallery view, but if that's too time consuming, then maybe keeping it at "X Results" is better, since it's more general.
4) When I apply filters on the dev site in gallery view, the page reverts back to list view and I have to switch it back to gallery. Can this be set so it stays on the view you were on when you applied the filters? 
5. Not sure about including the "Download" option for non AASHE staff in the gallery view, but we can discuss more next week. 

NIce work, go back to vacation!

**Comment by jamstooks** [comment]
Ok, I've

- [x] added a mouse-over for the list and gallery buttons
- [x] limited the the display of the toggle to the correct content types
- [x] fixed the issue where the filters reverted

The download link is only available to staff, which I think we discussed and makes sense to me.

Finally, when it comes to the _# of Resources_ part, it would still a lot of work to change it to read _# of images_ and we should probably hold off on for now. I think I like having it say "Resources" though, as that # will still be accurate. For example, if there are 2 resources with 3 images each, then 6 thumbnails will show up and top will say "2 Resources," which is still accurate. If it were to say "Results" then I think that might be more misleading than the alternative.

**Comment by jamstooks** [comment]
@monika-aashe @juliandsmith 

Ok, my dev server has a working version of this:

https://aashe-hub-dev-ben.herokuapp.com/browse/?search=&gallery_view=gallery

Please provide any feedback here, so that I can make any changes and publish this feature.

**Comment by juliandsmith** [comment]
Looks good to me!

**Comment by monika-aashe** [comment]
Looks good to me too!

**Comment by jamstooks** [comment]
Since the thumbnail process is making the staging site extremely slow and sometimes time out, we've had to develop a workaround where the thumbnails are create asynchronously when the images are first uploaded. This is mostly developed in the [celery](https://github.com/AASHE/hub/commits/celery) branch, but there are a few outstanding pieces:

- [ ] Decide if we even use celery… maybe synchronous is fast enough?
- [ ] add tests
- [ ] update templates to use generated thumbnails that are now stored on the model
- [ ] add placeholder images
- [ ] run thumbnailing on all existing images

**Comment by jamstooks** [comment]
Will use celery for now.
