### ISSUE TITLE
Copy date posted into date created field for case studies

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#318]
Crystal noticed that none of the case studies have creation dates currently, so trying to sort on this criteria doesn't work. Since case study creation dates are identical to case study submission/post dates, please copy the post date and into the creation date field for all previously submitted case studies.

**Comment by jamstooks** [comment]
...and how would you like those to be populated going forward? That field [is optional for case studies](https://github.com/AASHE/hub/issues/284#issuecomment-215143606) right now. Should it just auto-populate with the current date?

**Comment by juliandsmith** [comment]
Good question. In an ideal world, that question wouldn't even appear to the user on the case study form and would be auto-filled in with the submission date. 

If it the field still has to appear to the user, auto-populating it and making it required seems like an ok option. You could even call the field "Submission date" to make it clearer that this is what we are looking for. In the current wording, they may think we are asking about the date when the subject of the case study was "created," which actually isn't what we want.

**Comment by jamstooks** [comment]
So it really feels like what you're looking for is Case Studies to _not_ have the `date_created` property at all and that filter shouldn't really exist for it either.

But, since that "Date Created" filter is global, the `date_created` property should mirror the `date_submitted` property so that they aren't excluded from a global search? Does that sound right?

In the meantime, the fact that the "Date Created" filter isn't as useful for this content type as it is for others, when there is an alternative "Year Submitted" filter that does what you're looking for, doesn't feel like a prio:high issue to me.

**Comment by juliandsmith** [comment]
Yes, that sounds like it should work just fine. The key is that date created and date submitted aren't actually different properties when it comes to the case studies. So, if you can just not have a date created associated with case studies but still have it show up when someone does a global search based on date created, that would be great.

I'm not sure I understand your last paragraph though. Are you just saying that making the changes above should be a lower priority?

**Comment by jamstooks** [comment]
Right. I'm thinking this is pretty low on the priority list because date submitted and date created are the same. So, if you're looking to filter Case Studies, you can with the "Date Posted" filter.
