### ISSUE TITLE
Green colors not matching across pages

### ISSUE THREAD

**Issue by jamstooks** [AASHE/hub#35]
The "Download" and "Request a Change" buttons are different shades of green. We might want to use a contrasting color here, like blue or match the other greens on the site.

**Comment by bartTC** [comment]
Related: We have variables to have matching colors: https://github.com/AASHE/hub/blob/master/hub/static/scss/base.scss#L1-L3

**Comment by monika-aashe** [comment]
Another related question (lower priority) - is it possible for color theme under topics to match the color of the sustainability topic button? For example, Curriculum and Research are both light blue, so instead of green, the contrast color for those toolkits and resource lists would be light blue as well.

**Comment by bartTC** [comment]
I actually tried that and it didn't look good. The unity theme is pretty high key by default, and adding big blocks of color look off. You should try it out, but try very light high key colors.

**Comment by monika-aashe** [comment]
The overall theme that you are using looks great with a minimal amount of green contrasting drk grey and white. My question is about just substituting the green we're using now with other colors.
