### ISSUE TITLE
Always display "File", but include help-text when no content is available. 

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#359]
Text: "The submitter of this resource did not include any associated files."

Rationale:
Folks are confused about why some resources don't have associated files (usually for Conference Presentations, for which only about 40% have presentation files)

Need to decide whether this should apply to Conference Presentations only or across the board. 

May also decide to include it under "Link" and/or "Images".

**Comment by baronvonvaderham** [comment]
Since this ticket was submitted, display has changed slightly so that there is now a section "Links and Files" rather than having these in separate blocks.

As such, I've altered this slightly to conditionally display the copy you provided (modified to say "[...] associated files or links" instead of just files) if there are neither files or links present. If there is a link but no file, it just displays the link, it seemed awkward to put your copy below that.

From a UX standpoint, if the section "Links and Files" just shows a link or two, it follows that there are no files, and vice versa, but it makes sense to have your copy in lieu of the section not displaying at all to clarify that there is no bug, there is just nothing to show.
