### ISSUE TITLE
Paragraph breaks not recognized in block content

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#387]
Example: https://hub.aashe.org/_ad/block_content/block/19/change/ has three "paragraphs", but it displays as a single paragraph: https://hub.aashe.org/browse/types/academicprogram/

Hard to test out different variations because of the 12-hour caching.

**Comment by baronvonvaderham** [comment]
This is resolved as per our discussion on the hub call today. We should probably update any documentation we have on markdown to make it more clear, but otherwise this is now working. The tab links not switching tabs is a different but related issue I'll resolve today, changing those from links manually added in django-block-content pieces to automatically generated buttons under the text block (which will allow interaction with bootstrap to make the tab switch).
