### ISSUE TITLE
Admin exports not downloading

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#396]
I tried downloading a csv, xls, xlsx, and html export of the Academic Programs, and the request timed out. 

Also want to verify whether the exports will include all data from the submission forms (rather than just the view within the Admin panes).

**Comment by monika-aashe** [comment]
A student is requesting access to this for research. Aim for mid-October

**Comment by jamstooks** [comment]
The package we're using to do this, [django-import-export](https://github.com/django-import-export/django-import-export/) doesn't support background-processing and it [doesn't look like they plan to](https://github.com/django-import-export/django-import-export/issues/386).

I have created a new issue (#402) to include this feature, but it's going to be a pretty time-intensive process and cannot be achieved in our current milestone.

In the meantime, export requests can be run manually by IT (because we can run the export locally without timeout restrictions). So, please let us know via IT Support tickets when you need an export.
