### ISSUE TITLE
Revisit "Year Posted" filter and possibly remove

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#404]
to avoid confusion with the more relevant date field, "Year created, published, or presented"

**Comment by monika-aashe** [comment]
Do we need this for anything that is based on submission date deadlines? Awards?

**Comment by juliandsmith** [comment]
Year posted is potentially relevant for case studies (since awards are based on when the case study was submitted rather than the date of the project described in the case study. Unless we can just remove the date created field from the case study form and automatically enter the submission date, I think we probably do need to keep this.

**Comment by monika-aashe** [comment]
Closing since year posted is still important to use from time to time.
