### ISSUE TITLE
Map not working under Conference Presentations and Publications

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#422]
It shows up as grey or black, instead of showing a zoomable map.

**Comment by monika-aashe** [comment]
See Example: https://hub.aashe.org/browse/types/presentation/#map-panel

**Comment by monika-aashe** [comment]
@dodget - I'm reopening this because even though it was fixed a while ago, the maps are once again not working for Publications and Conference Presentations. Any idea why that would happen again?

**Comment by dodget** [comment]
There isn't much info in this issue as to how it was resolved and closed on 5/31/2017. I'll have to take a fresh look at it. My guess would be that there is a javascript issue (but there are no errors) or an issue with the data that it is trying to display.

**Comment by monika-aashe** [comment]
I wondered that too. I think this was a ticket that @unbracketed worked on at the end of last year.

**Comment by dodget** [comment]
In the latest deploy to production, I pinned the map with static coordinates, so the scaling and zoom of the map can't be as far off as they were in this case. These two content types have functioning maps once again.

Some geographic regions do repeat. This due to limitations in google map's 'zoom' option. I did the best that I could to fit all participating institutions, without cutting any off the map.

If you notice any issues, please re-open. Closing, now.
