### ISSUE TITLE
Unable to submit resources and other . . . resources.

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#430]
Unable to submit resources, case studies, conference presentations, course materials, publications, and tools. For some reason, academic programs and research centers still seem to work.

**Comment by monika-aashe** [comment]
One difference with these two content types to look into: Academic Programs and Research Centers/Institutes are the only content types that don't have a photo or file upload option.

**Comment by jamstooks** [comment]
Hey @rerb - I believe I've fixed this bug, but I will leave it to you to accept the pull-request and release the code (unless you advise me otherwise). There are also a few more follow-ups...

We'll need a new bug, as I described in my email for the Organization Type filter, as the iss isn't getting the Carnegie class data from MemberSuite. I've disabled that filter for now so that tests pass.

- [ ] add issue to [iss](https://github.com/AASHE/iss/) app to collect `primary_org` and `title` or `position`
- [ ] add issue to [hub](https://github.com/AASHE/hub/) to update the way the Org Type filter works.

**Comment by rerb** [comment]
@jamstooks -- we need primary_org and title or position on the portaluser object, correct?  Confirming since you mention iss in this context but portaluser stuff is in membersuite_api_client/security.

Also, these:

> a new bug, as I described in my email for the Organization Type filter, as the iss isn't getting the Carnegie class data from MemberSuite.

and

> add issue to hub to update the way the Org Type filter works.

Are they the same or separate issues?

**Comment by jamstooks** [comment]
Good question, @rerb! Sorry about that. Yes, I meant `primary_org` and `title` on the `PortalUser` object. So a better task list would be:

Hub Author issue
  - [ ] issue in [django-membersuite-auth](https://github.com/AASHE/django-membersuite-auth) app to collect `primary_org` and `title` or `position`
  - [ ] issue in [hub](https://github.com/AASHE/hub/) to re-enable auto-populate form for authors

Hub Org Type Filter
  - [x] issue in [hub](https://github.com/AASHE/hub/) to update the way the Org Type filter works
  - [ ] issue in [iss](https://github.com/AASHE/iss/) app to collect OrgType from MemberSuite

By removing the Org Type filter and removing the author author auto-populate values, I've at least stopped the errors being thrown.

**Comment by rerb** [comment]
for anybody watching this issue, note that the initial problem, an inability to add certain types of resources, has been fixed for a while -- this issue is just hanging around until ben's notes get turned into other issues.
