### ISSUE TITLE
Suggestion: Rename "Apply Filters" button to "Search"

### ISSUE THREAD

**Issue by rerb** [AASHE/hub#452]

**Comment by juliandsmith** [comment]
FWIW, I'm hesitant about this change because clicking this button doesn't create a new search - it just modifies the results of a previous search. For example, if you've already searched for "bottled water", and changes you make on the filters menu only changes the results of that existing search - it doesn't start a new search.

**Comment by rerb** [comment]
Good point.  Actually, though, a new search is performed when the Apply Filters button is pressed.  It's just a combination of the search terms and the filters -- as all searches are over there.

"Apply Filters" sounds like a technical term to me.  Once you know how the Hub search works -- once you have a mental model of what it's doing under the covers -- "Apply filters" makes sense.  But that button's for newbies, too.  I think it adds friction as slightly increased cognitive load -- like using an abbreviation that takes a fraction of a second to translate.  "Apply Filters?  I guess that's what I want to do.  It's the only button there."  vs.  "Ah! Search button!"

Chris Harris has some free time lately.  I can ask him to get him started on an IT Button Name Policy. ;-)

**Comment by rerb** [comment]
You are correct, "Apply Filters" *is* a better name.  Thanks, Julian.
