### ISSUE TITLE
Special characters don't look right in organization field

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#460]
Certain special characters don't seem to be showing up properly. For example, "Federal University of Uberlândia" shows up as "[Federal University of Uberl├óndia](https://hub.aashe.org/browse/presentation/10670/gloria-campus-of-federal-university-of-uberlandia-planning-a-sustainable-campus-with-public-participation)". 

As you can see in the linked example, this problem isn't universal - the "â" shows up correctly in the title but not the organization field. This suggests it is an AMS/ISS issue. Sure enough, this organization [doesn't show up correctly in Membersuite](https://console.membersuite.com/app/console/organization/view?c=6faf90e4-0007-c540-bdae-0b3cac9d1e93&updateQuickSearch=False). 

@jessicaaasheaashe Can you ask Membersuite about this?

**Comment by rerb** [comment]
The unicode characters are incorrect in MemberSuite, so they'll bleed over into the Hub, Stars. the Bulletin, etc.  Need to fix in MemberSuite, and the changes will ripple out to the other systems.

I'll guess the resource listed was entered through the Hub interface, which does seem to handle unicode characters correctly -- that's why the â is right in the resource title.  (And it's wrong in the organization name because that's what comes from MemberSuite.)

**Comment by jessicaaasheaashe** [comment]
All,

I think this was a migration error.  I think it would be easier to just correct these in Member Suite manually instead of asking them to do some sort of global fix.  I just fixed the Federal University of Uberlândia one.  If you could identify other records where this is happening, let's go ahead and fix manually.  

Sincerely,
Jessica

**Comment by juliandsmith** [comment]
Got it! I've started fixing manually in MS and will continue to do this. I'll close this ticket here.
