### ISSUE TITLE
Bug in adding images in Admin

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#470]
Every time I try to add an image in the Hub Admin, it does not display correctly on our site. This was not the case before, but it has been an issue before that was fixed

Here are two examples where I added images, and the new images don't show up:
https://hub.aashe.org/browse/photograph/18080/Sustainability-in-Science-Museums-Fellows
https://hub.aashe.org/browse/photograph/18098/Bates-College-Students-Install-Solar

**Comment by unbracketed** [comment]
- [x] code fix to ensure thumbnails are generated for new images
- [ ] generate any missing thumbnails for existing images in the system

**Comment by unbracketed** [comment]
This should be working now.  There will be a 15 second delay between saving a new image and when the thumbnail version will be available on the site, so if you go to the page right away, you'll see the placeholder until the thumbnails are available.

The reason for this delay is that there appears to be a race condition that happens during the save/thumbnail steps.  The sequence is basically like:

1. Create an entry for the source image in the database and transfer the file contents to AWS S3
2. Create a background task that loads the same image back from storage and runs thumbnail processing

As far as I can tell the problem is that when the task requests the image from storage, storage reports that it isn't there yet and so the thumbnail operation fails.  Waiting a small bit of time helps ensure that the original transfer to storage is complete and that the S3 bucket will be in a state to expose the file for the next 'get' operation.  15 seconds was chosen arbitrarily - a couple of seconds is probably sufficient.  

```
brian@Miller:~/code/virtualenvs/AASHE/src/hub$ heroku run 'python manage.py thumbnail_report' -a aashe-hub-prod
Running python manage.py thumbnail_report on ⬢ aashe-hub-prod... up, run.3543 (Standard-1X)
Total images: 1716
Broken small thumbs: 2
Broken medium thumbs: 2
brian@Miller:~/code/virtualenvs/AASHE/src/hub$ heroku run 'python manage.py create_thumbnails' -a aashe-hub-prod                                                        
Running python manage.py create_thumbnails on ⬢ aashe-hub-prod... up, run.3691 (Standard-1X)

-------------------------
Generating thumbnails for 1716 Images
-------------------------

brian@Miller:~/code/virtualenvs/AASHE/src/hub$ heroku run 'python manage.py thumbnail_report' -a aashe-hub-prod
Running python manage.py thumbnail_report on ⬢ aashe-hub-prod... up, run.8077 (Standard-1X)
Total images: 1716
Broken small thumbs: 0
Broken medium thumbs: 0
```

**Comment by monika-aashe** [comment]
This is working great now, thanks @unbracketed !
