### ISSUE TITLE
Orgs to delete manually from Hub

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#488]
Please refer to the list of organizations and corresponding IDs [in the Deleted Orgs tab of this Google Sheet](https://docs.google.com/spreadsheets/d/1L0PzGT7G9dhds8dEfZ4gcPj7tOa0scoPtVxnqkIJHrk/edit#gid=1200532481).

Note: Many of these are duplicates, so it's important that the Org ID matches to avoid deleting the wrong organization within the Hub.

**Comment by dodget** [comment]
@monika-aashe - Is the process for this to just -carefully- delete these orgs through the Hub Admin?

**Comment by monika-aashe** [comment]
Not the admin (which I would be able to do). I believe they have to be deleted in the ISS database, but I would check with @rerb or @unbracketed to double-check.

**Comment by rerb** [comment]
@dodget - one approach here would be to expose the iss.Organization records in the admin, which would allow Monika to delete orgs at will.  Would require an admin.py in the iss app that describes how to show orgs, what fields to make editable, etc.  Once the iss application has an admin.py, I think it'll "automatically" show up in the Hub admin under the heading "ISS".

**Comment by juliandsmith** [comment]
You may know this already, but we can actually already [access the list of orgs in the hub](https://hub.aashe.org/_ad/metadata/organization/). However, we can't delete orgs or edit the associated data. I'm not sure we want to be able to make edits - we should be making them directly in Membersuite - but since ISS doesn't know when an org has been deleted from MS, having the ability to delete orgs would certainly be helpful.

**Comment by dodget** [comment]
@rerb - I added an admin.py in the ISS app, and issued a [pull request](https://github.com/AASHE/iss/pull/19). I think this should expose the iss.Organizations table to any project with the ISS installed.

**Comment by rerb** [comment]
@dodget - PR is good, but we should also bump up the version of ISS -- it's specified in setup.py.  Now it's 2.5.10, so since you've added a feature, we should bump to 2.6 there.  Then create a release of ISS in Github that's version 2.6.  Then, to get Hub to use the updated ISS, we need up update the reference in Hub's requirements.txt to point to the new version.  Does that make sense?

What needs to be done:

1. change version in iss/setup.py to 2.6 (make the change on the same branch you used to make the previous change and it'll just roll up into this same PR).
2. cut a new release on Github at https://github.com/AASHE/iss/releases/new. Name it v2.6.
3. update hub/requirements.txt to point to new ISS release.

**Comment by monika-aashe** [comment]
Question, @dodget - is it possible to add two variables to this list? 
- Membersuite ID (right now, it displays the account number but this is less than ideal since that number doesn't show up in the AMS (it's tricky to figure out which should be deleted as a result). 
- Can we add something along the lines of "number of resources associated with this resource"?

**Comment by dodget** [comment]
I see. I only got access to membersuite today, so I see the constraint. Changing to Membersuite ID will be no problem.

For the second bullet, I'll have to research it more. From my reading of the model, ISS orgs don't keep a record of what they are associated with. And because the ISS is a separate database, and managed as an imported package into the hub, I'm not sure I could get access to Hub data from inside the ISS (which is where this admin table is being produced). If I could, I think it would be simple.

**Comment by monika-aashe** [comment]
Okay, no worries, the first fix will be awesome on its own if the second isn't easily doable.

**Comment by monika-aashe** [comment]
Just to clarify, both account number and membersuite ID would be helpful (Hub URLs still use the former).

**Comment by dodget** [comment]
Sounds good!

**Comment by dodget** [comment]
@monika-aashe - I'll make the records searchable on name, and memberuite ID (the ID will be an exact match). Is there a reason to make the records searchable on account number? In my testing, allowing searching on both MS ID and account number to be searched just produces confusing results.

**Comment by monika-aashe** [comment]
Searchable by membersuite ID is fine, but I was actually thinking that the membersuite ID number would show up in the table listed below the search bar. That way, if I search on institution name, it'll pull up any/all dupes in the table, and I'll be able to see which one is the one that needs to be deleted.

**Comment by dodget** [comment]
Yes, membersuite ID will be in the table. I'll submit the changes for merging!

**Comment by dodget** [comment]
@monika-aashe - The requested changes should be appearing in production, now. Let me know if anything needs to be tweaked!

**Comment by monika-aashe** [comment]
All looks good, closing!
