### ISSUE TITLE
Affirmation of ownership issues

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#75]
On certain content types, Affirmation of ownership check box is required even if no material has been uploaded. We want this option to show up and be required if a file has been uploaded, and we only want the affirmation of ownership to show up once for any content type.

Here is how Affirmation of Ownership should be displayed:
REQUIRED (because an upload is required)
- Conference Presentations
- Photographs

CONDITIONALLY REQUIRED (should be required only if a document is uploaded)
- Case Studies
- Publications
- Course Materials
- Tools
- Outreach Materials

REMOVED (No upload fields so no need for affirmation)
- Academic Programs
- Research Centers & Institutes
- Videos

See row 27 in the following sheet: https://docs.google.com/spreadsheets/d/1ADsnCZXKU1lhA4GHc2xhsY5ddLRi7kgvYJLSTHZKlmw/edit#gid=935008516

**Comment by jamstooks** [comment]
Why not simply say that there's an affirmation of ownership for each file and image? It emphasizes that the affirmation of ownership is relevant for every file and has the added benefit of making the interface clear and strait forward. Here's my suggestion:

**Conference Presentations**
- 1 file upload required
- maximum might not be required as people might want to upload a PDF/PPT.

**Photographs**
- 1 file upload
- 1 file max (since we really only want to have one photo per photo resource)
- question: how can we streamline the process for folks who want to upload a bunch of photos?

**Case Studies, Publications, Course Materials, Tools, Outreach Materials**
- No uploads required - those files that are uploaded have the affirmation associated with them

**Academic Programs, Research Centers & Institutes, Videos**
- No uploads allowed (Image/File sections don't show up.

**Bonus**
This has the added benefit that it'd be easy to add additional content-types down the road... and just apply a property like `max_images=1` and `min_images=1` for that content-type to indicate that one and only one image is required for the new content-type.

As an example Conference Presentations would have `min_files=1` and `max_files` might be 3 or so...

**Comment by jamstooks** [comment]
With this method accepted on our latest call, I'm going to close this ticket in favor of #140.
