### ISSUE TITLE
Admin - Improvements

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#81]
We would like to make the following columns in the admin (http://aashe-hub-dev.herokuapp.com/admin/content/contenttype/?o=6) sortable: 
- Edit Object (but rename to "Title")
- Content Type

Right now, the "select" option at the right of the admin list has no purpose. It would be useful to incorporate the "bulk select" so that it worked properly. 

Also would be useful to have a "delete selected" and an "unpublish selected" option at the bottom. If doable, also "make all open with login/public/member-only.

**Comment by monika-aashe** [comment]
Are there any other ways the bulk select feature could be useful?

**Comment by baronvonvaderham** [comment]
Currently working on this ticket and have successfully added batch update features to publish, unpublish (marks the item as "new" again), and decline.

Is it ok if these actions don't trigger the email notifications I see elsewhere? If those need to happen I can find a way, but otherwise I can move on to the column sorting part.

**Comment by monika-aashe** [comment]
I don't think we need to send a new email to the submitter when we change from published to unpublished. That would probably be confusing. Just emails for initial changes from new to published and new to unpublished (when saved)

**Comment by baronvonvaderham** [comment]
That's what I was thinking. Ok I'll add in methods to trigger notifications in those cases.

**Comment by baronvonvaderham** [comment]
Test cases added
