### ISSUE TITLE
Shortened URLs should be valid

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#95]
I get a weird pop-up warning, "Please enter a URL" when I entered "www.aashe.org" into a website field. When entering "http://www.aashe.org/, it went through okay. The website should recognize shortened URLs that begin with www. as valid, as well as those that start with http://

**Comment by jamstooks** [comment]
This is a very common practice in most web-forms and something we use in all our sites. The reason we require the http:// is so that we can validate the url. It's hard to validate something like "mywordfile.pdf" . Is that a domain or is that someone typing the wrong thing into the field.

Unless you have a paramount objection, I'd prefer not to do this as it would require going against the default functionality of a URL input field and significant extra work.

**Comment by monika-aashe** [comment]
No objections - we can simply add helptext to indicate that the URL must begin with http://
