### ISSUE TITLE
Publications Submission form

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/hub#96]
- Organization(s) - field is required for the Publications Content type. This is the only content type where Organization(s) should be optional (high-priority). 

- Type of Material is currently optional. This must be required. This also does not show up in the Resource Detail list, even when something is selected: http://aashe-hub-dev.herokuapp.com/browse/publication/12/Going-Beyond-Green-The-Why-and-How-of-Integrating-Sustainability-Into-the-Marketing-Curriculum (medium priority)

**Comment by jamstooks** [comment]
- Calendar widget isn't optimal. In some cases, only the year or month and year are available. It would be better to have Year | Month | Day - three separate fields all in a row, and only the year is required.

This applies to more than one content type and warrants discussion on it's own: #116

- When submitting a website under the "Website" field (not under Optional metadata), the website field does not appear once the resource is approved: http://aashe-hub-dev.herokuapp.com/browse/publication/47/2015-Sustainability-Staffing-Survey - it does show up in admin.

This applies to multiple content types, so I have broken it out as one ticket: #114

- File upload and website section in Optional metadata not necessary, since the both are provided above (though would be good to allow up to three file uploads above). On the detail page (), uploaded files also show up in two places. All uploaded files should be in one place only.

This is addressed in #73.

**Comment by jamstooks** [comment]
Fixed in 581f76b3dc1e5267e94258a9aceb070e583dbbe4 and db75ffe4029ef66ac07a756c7eca3d49b62af760

**Comment by jamstooks** [comment]
@monika-aashe I've update the [hub fields document](https://docs.google.com/spreadsheets/d/1ADsnCZXKU1lhA4GHc2xhsY5ddLRi7kgvYJLSTHZKlmw/edit#gid=935008516) to reflect an "r" for type of material.
